// The demo instance the mockup depicts (#226): three archetypal clients the
// Foundations epic's day-rate/continuous/retainer billing shapes were
// generalised from, each carrying the evidence a real one would — days in
// every lifecycle state, a paid invoice, an overdue one, one due soon, an
// unrebilled expense, a clause note, an archived approval email and two
// pending proposals from it.
//
// Lives under `src/lib/server`, not `scripts/`, so `pnpm check` type-checks
// it the same way it does every other file here (the root `tsconfig.json`'s
// `include` — generated by `svelte-kit sync` — covers `src/**`, not
// `scripts/**`). `scripts/seed-demo.ts` is the thin plain-node entrypoint
// that actually runs it, the same split `scripts/runner.ts` and
// `src/lib/server/runner/cli.ts` already use, and for the same reason: real
// logic gets real type checking, and the entrypoint stays trivial enough
// that it does not need its own.
//
// Every write here goes through the same repository functions the app
// itself calls — `createClient`, `createContract`, `createWorkUnit`,
// `createInvoice`, `createCeiling`, and so on — never a raw insert (the one
// exception, `fiscal_profile`, has no repository at all: every test in this
// tree writes it the same way, a typed `db.insert(fiscalProfile)`, since
// AGENTS.md's "one fiscal profile" has never needed one). That is what
// makes a wrong shape here a `pnpm check` failure instead of a silent bad
// row: #226 exists because a throwaway `.test.ts` seed set a ceiling's
// `alertLevels` to `{ id, threshold, severity }`, not `CeilingAlertLevel`'s
// `{ ratio, label }`, and nothing caught it because vitest strips types
// without checking them.
//
// No single transaction wraps the whole thing: `createClient`,
// `createContract` and `createRateCard` commit on their own (none of the
// three accepts a caller's transaction — see each one's own signature in
// `repositories/`), the same way a human filling in the client, then the
// contract, then its rate card through the UI would produce three separate
// commits. This seed follows that shape rather than fighting it.
//
// Idempotent: gated on Nordwind Logistics' `tax_id` not already existing.
// A second run finds the row, reports the instance is already seeded, and
// writes nothing further.

import { eq } from 'drizzle-orm';
import { db } from '$lib/server/db';
import { client as clientTable, fiscalProfile } from '$lib/server/db/schema';
import type { TransitionActor } from '$lib/server/db/schema/work-unit';
import { minorUnitsFromMajor, scaleMinorUnits, type MinorUnits } from '$lib/money';
import {
	evaluateInvoiceCharges,
	resolveDefaultTaxTreatment,
	type ResolvedTaxTreatment
} from '$lib/server/fiscal/pack';
import { itFlatRatePack } from '$lib/server/fiscal/packs/it-flat-rate';
import { createClient } from '$lib/server/repositories/client';
import { createContract } from '$lib/server/repositories/contract';
import { createRateCard } from '$lib/server/repositories/rate-card';
import { createCeiling } from '$lib/server/repositories/ceiling';
import { createWorkUnit, transitionWorkUnit } from '$lib/server/repositories/work-unit';
import { createApproval } from '$lib/server/repositories/approval';
import {
	createInvoice,
	recordPayment,
	type InvoiceLineInput
} from '$lib/server/repositories/invoice';
import { createExpense } from '$lib/server/repositories/expense';
import { createClauseNote } from '$lib/server/repositories/clause-note';
import { storeDocument } from '$lib/server/repositories/document';
import { createProposal } from '$lib/server/repositories/proposal';

/** The fixed "today" this instance is built around (#226: "Today is 13
 * August 2026"). Every relative date below — the overdue invoice, the one
 * due in three days, the day recorded without approval — is chosen against
 * this constant, never the real clock, so the seeded instance reads the
 * same regardless of when it is actually run. Not read programmatically
 * (every date below is a literal, chosen with this in mind); kept as a
 * named constant so a reviewer checking "34 days overdue" or "due in three
 * days" has the anchor written down once, in one place, rather than having
 * to reconstruct today's date from the issue text. */
const TODAY = '2026-08-13';
void TODAY;

const LORENZO: TransitionActor = { kind: 'human', email: 'lorenzo@example.com' };

function eur(major: number): MinorUnits {
	return minorUnitsFromMajor(major, 'EUR');
}

function eml(text: string): Uint8Array {
	return new TextEncoder().encode(text);
}

/** The one tax treatment every invoice in this seed takes: the active
 * fiscal profile is `it-flat-rate` throughout, and that pack applies its
 * VAT-exempt treatment unconditionally (#216) — so this is resolved once,
 * not per invoice. */
const TAX_TREATMENT: ResolvedTaxTreatment = (() => {
	const treatment = resolveDefaultTaxTreatment(itFlatRatePack);
	if (!treatment) throw new Error('it-flat-rate declares no default treatment');
	return treatment;
})();

/** An invoice's stamp duty and social charge, both a function of its own
 * taxable total (#226's stamp-duty threshold and INPS surcharge) —
 * `evaluateInvoiceCharges` (`fiscal/pack.ts`) itself, the same pure
 * function `resolveInvoiceTax` (`repositories/invoice-form.ts`) calls; not
 * reimplemented here, only not imported through that module, which also
 * pulls in compiled Paraglide messages this seed has no reason to depend
 * on (see `resolveInvoiceTax`'s own doc comment for why one exists). */
function chargesFor(taxableAmount: MinorUnits) {
	return evaluateInvoiceCharges(itFlatRatePack, { invoiceTotal: taxableAmount });
}

/** One invoice line for a single billed day, using the seed's one uniform
 * tax treatment. */
function dayLine(description: string, workUnitId: string, dayRate: MinorUnits): InvoiceLineInput {
	return {
		description,
		quantity: 1,
		unitPrice: dayRate,
		amount: dayRate,
		taxRate: TAX_TREATMENT.taxRate,
		taxTreatmentCode: TAX_TREATMENT.code,
		workUnitIds: [workUnitId]
	};
}

/** Creates an invoice from already-built lines, resolving the invoice-level
 * fields (`taxTreatmentCode`, `statutoryReference`, `stampDuty`,
 * `socialCharge`) from their sum the same way `repositories/invoice-form.ts`
 * does for a human filling in the invoice screen. */
async function createTaxedInvoice(
	contractId: string,
	number: string,
	issueDate: string,
	dueDate: string | null,
	lines: InvoiceLineInput[]
) {
	const taxableAmount = lines.reduce(
		(sum, line) => (sum + line.amount) as MinorUnits,
		0 as MinorUnits
	);
	const charges = chargesFor(taxableAmount);
	return createInvoice(
		{
			contractId,
			number,
			issueDate,
			documentType: 'invoice',
			currency: 'EUR',
			taxTreatmentCode: TAX_TREATMENT.code,
			statutoryReference: TAX_TREATMENT.legalText,
			stampDuty: charges.stampDuty,
			socialCharge: charges.socialCharge,
			dueDate,
			paymentMethod: null,
			iban: null,
			transmissionId: null,
			lines
		},
		LORENZO,
		'issued',
		undefined
	);
}

async function seedFiscalProfile() {
	await db.insert(fiscalProfile).values({
		packId: itFlatRatePack.id,
		packVersion: itFlatRatePack.version,
		validFrom: '2024-01-01',
		validTo: null
	});
}

/**
 * Nordwind Logistics: day rate, prior approval required. Ten days, one per
 * `work_unit_state` value, most of them sharing one archived approval email
 * — several days from one approval is #209's own contract, not a special
 * case. `2026/014` is the paid invoice; `2026/009` is the disputed one;
 * `2026/012` is invoiced and half paid (#212), the partial-payment case
 * the other two lifecycle days land on.
 */
async function seedNordwind() {
	const clientRow = await createClient({
		legalName: 'Nordwind Logistics S.r.l.',
		taxId: 'IT01234560001',
		vatId: 'IT01234560001',
		country: 'IT',
		addressLine1: 'Via dei Trasporti 12',
		addressLine2: null,
		addressCity: 'Verona',
		addressPostalCode: '37122',
		addressRegion: 'VR',
		noticeChannel: 'email',
		// #259: has its own CodiceDestinatario on file — the routing case
		// an invoice detail screen resolves to `'sdi_code'`.
		sdiCode: 'ABC1234',
		pecAddress: null,
		contacts: [
			{
				name: 'Elena Marchetti',
				email: 'elena.marchetti@nordwindlogistics.example',
				phone: '+39 045 555 0101',
				role: 'Direttrice operativa',
				canApprove: true
			}
		]
	});

	const contractRow = await createContract({
		clientId: clientRow.id,
		title: 'Consulenza operativa — Nordwind Logistics',
		signedDocumentReference: null,
		startsOn: '2025-01-01',
		endsOn: null,
		renewalType: 'tacit',
		renewalNoticeDays: 60,
		terminationNoticeDays: 30,
		paymentTerms: { kind: 'net', days: 30 },
		invoicingCadence: 'monthly',
		currency: 'EUR',
		taxTreatment: 'Regime forfettario',
		requiresPriorApproval: true,
		templateLanguage: 'it',
		expensePolicy: { kind: 'reimbursed_at_cost' },
		requiresExpensePreAuthorisation: false,
		status: 'active'
	});

	await createRateCard({
		contractId: contractRow.id,
		validFrom: '2025-01-01',
		validTo: null,
		kind: 'daily',
		amount: 700,
		unit: 'day',
		allowedFractions: [1, 0.5],
		minimumHours: null,
		disbursementPeriod: null
	});

	await createClauseNote({
		contractId: contractRow.id,
		clauseReference: 'Art. 7.2',
		verbatimText:
			'Le spese di trasferta documentate sono rimborsate a piè di lista, previa comunicazione scritta al referente entro 5 giorni lavorativi dal loro sostenimento.',
		interpretationAdopted:
			'La comunicazione via email al referente operativo, anche successiva alla trasferta ma entro il termine, è considerata comunicazione scritta valida ai fini della clausola.',
		notes: null
	});

	await createExpense(
		{
			contractId: contractRow.id,
			date: '2026-07-25',
			description: 'Trasferta Verona — biglietto treno e pernottamento',
			amount: eur(185),
			preAuthorised: true,
			authorisationReference: 'Confermato via email da Elena Marchetti, 24/07/2026'
		},
		null
	);

	const dayRate = eur(700);

	// The archived approval email: one document, one approval, covering
	// several of the days below (#209 — "several proposals from one source
	// document share one approval, never one each" applies just as much to
	// a human's own batch of days as to an accepted proposal).
	const approvalRow = await createApproval({
		contractId: contractRow.id,
		channel: 'email',
		sender: 'elena.marchetti@nordwindlogistics.example',
		receivedAt: new Date('2026-07-15T08:40:00Z'),
		messageId: '<approvazione-luglio-2026@nordwindlogistics.example>',
		excerpt:
			"confermo le giornate concordate per la formazione del team logistica, l'ottimizzazione delle rotte settimanali, l'audit trimestrale delle scorte e la pianificazione della manutenzione flotta. Procedi pure.",
		origin: { kind: 'manual' },
		document: {
			bytes: eml(
				'Da: Elena Marchetti <elena.marchetti@nordwindlogistics.example>\n' +
					'A: lorenzo@example.com\n' +
					'Data: 15 lug 2026, 08:40\n' +
					'Oggetto: Approvazione giornate luglio\n\n' +
					'Ciao Lorenzo,\n' +
					"confermo le giornate concordate per la formazione del team logistica, l'ottimizzazione delle rotte settimanali, l'audit trimestrale delle scorte e la pianificazione della manutenzione flotta. Procedi pure.\n\n" +
					'Elena\n'
			),
			mime: 'message/rfc822',
			originalName: 'approvazione-luglio-2026.eml',
			provenance: 'mail',
			confidential: false
		}
	});

	// 1. proposed — nothing decided yet.
	await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-08-10',
			quantity: 1,
			scope: 'Revisione flusso di carico presso hub Verona'
		},
		LORENZO,
		'proposta in attesa di conferma scritta'
	);

	// 2. approved — confirmed, not yet worked.
	const approvedDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-08-05',
			quantity: 1,
			scope: 'Sopralluogo magazzino automatizzato'
		},
		LORENZO,
		'proposta in attesa di conferma scritta'
	);
	await transitionWorkUnit(
		approvedDay.id,
		{ state: 'approved', approvalId: approvalRow.id },
		LORENZO,
		'confermata via email da Elena Marchetti'
	);

	// 3. worked — recorded worked with the approval already on file.
	await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-07-28',
			quantity: 1,
			scope: 'Formazione team logistica',
			state: 'worked',
			approvalId: approvalRow.id
		},
		LORENZO,
		'giornata svolta come da approvazione del 15 luglio'
	);

	// 4. worked_without_approval — recorded worked with no approval on
	// file; the state machine trigger lands it here automatically (#23).
	await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-07-21',
			quantity: 1,
			scope: 'Intervento urgente su blocco spedizioni',
			state: 'worked'
		},
		LORENZO,
		'intervento urgente confermato solo per telefono, nessuna approvazione scritta'
	);

	// 5. invoiced — billed, partially paid (#212): a client who sends
	// half is exactly the case the ageing list and the cash-basis ceiling
	// both have to keep showing correctly, not a special case that
	// disappears once collected in full.
	const invoicedDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-05-20',
			quantity: 1,
			scope: 'Riconciliazione inventario mensile',
			state: 'worked',
			approvalId: approvalRow.id
		},
		LORENZO,
		'giornata svolta come da approvazione del 15 luglio'
	);
	const partlyPaidInvoice = await createTaxedInvoice(
		contractRow.id,
		'2026/012',
		'2026-05-20',
		null,
		[dayLine('Riconciliazione inventario mensile — 20/05/2026', invoicedDay.id, dayRate)]
	);
	await recordPayment(partlyPaidInvoice.id, {
		amount: scaleMinorUnits(partlyPaidInvoice.total, 0.5),
		date: '2026-07-05',
		method: 'bonifico',
		reference: 'Acconto — bonifico del 05/07/2026'
	});

	// 6. paid — billed and collected: 2026/014, the paid invoice #226 names.
	const paidDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-06-15',
			quantity: 1,
			scope: 'Ottimizzazione rotte settimanali',
			state: 'worked',
			approvalId: approvalRow.id
		},
		LORENZO,
		'giornata svolta come da approvazione del 15 luglio'
	);
	const paidInvoice = await createTaxedInvoice(contractRow.id, '2026/014', '2026-06-30', null, [
		dayLine('Ottimizzazione rotte settimanali — 15/06/2026', paidDay.id, dayRate)
	]);
	await recordPayment(paidInvoice.id, { amount: paidInvoice.total, date: '2026-07-10' });
	await transitionWorkUnit(
		paidDay.id,
		{ state: 'paid' },
		LORENZO,
		'incasso registrato il 10/07/2026'
	);

	// 7. disputed — billed, then contested.
	const disputedDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-06-01',
			quantity: 1,
			scope: 'Audit scorte trimestrale',
			state: 'worked',
			approvalId: approvalRow.id
		},
		LORENZO,
		'giornata svolta come da approvazione del 15 luglio'
	);
	await createTaxedInvoice(contractRow.id, '2026/009', '2026-06-05', null, [
		dayLine('Audit scorte trimestrale — 01/06/2026', disputedDay.id, dayRate)
	]);
	await transitionWorkUnit(
		disputedDay.id,
		{ state: 'disputed' },
		LORENZO,
		'il cliente contesta la quantità fatturata, in attesa di chiarimento'
	);

	// 8. revoked — approved, then withdrawn before it was worked.
	const revokedDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-05-10',
			quantity: 1,
			scope: 'Pianificazione manutenzione flotta'
		},
		LORENZO,
		'proposta in attesa di conferma scritta'
	);
	await transitionWorkUnit(
		revokedDay.id,
		{ state: 'approved', approvalId: approvalRow.id },
		LORENZO,
		'confermata via email da Elena Marchetti'
	);
	await transitionWorkUnit(
		revokedDay.id,
		{ state: 'revoked' },
		LORENZO,
		'intervento non più necessario, revocato dal cliente prima di essere svolto'
	);

	// 9. rejected — proposed, then declined.
	const rejectedDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-05-01',
			quantity: 1,
			scope: 'Ipotesi ampliamento turno notturno'
		},
		LORENZO,
		'proposta in attesa di conferma scritta'
	);
	await transitionWorkUnit(
		rejectedDay.id,
		{ state: 'rejected' },
		LORENZO,
		'il cliente ha deciso di non procedere'
	);

	// 10. unbillable — entered the risk state with no recovery, and stays
	// there: no late approval ever arrived.
	const unbillableDay = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-04-15',
			quantity: 1,
			scope: 'Sopralluogo preliminare non confermato',
			state: 'worked'
		},
		LORENZO,
		'sopralluogo svolto senza attendere conferma scritta'
	);
	await transitionWorkUnit(
		unbillableDay.id,
		{ state: 'unbillable' },
		LORENZO,
		'nessuna approvazione mai arrivata, giornata non fatturabile'
	);

	// Two pending proposals from one message — never decided.
	const proposalsDocument = await storeDocument({
		bytes: eml(
			'Da: Elena Marchetti <elena.marchetti@nordwindlogistics.example>\n' +
				'A: lorenzo@example.com\n' +
				'Data: 20 ago 2026, 09:05\n' +
				'Oggetto: Giornate fine agosto\n\n' +
				'Ciao Lorenzo, per fine mese ti confermo la revisione dei contratti fornitori il 24 e la chiusura mensile di magazzino il 25. Grazie, Elena\n'
		),
		mime: 'message/rfc822',
		originalName: 'giornate-fine-agosto.eml',
		provenance: 'mail',
		contractId: contractRow.id,
		confidential: false,
		ownerType: 'contract',
		ownerId: contractRow.id
	});
	await createProposal({
		documentId: proposalsDocument.id,
		contractId: contractRow.id,
		targetType: 'work_unit',
		proposedFields: { date: '2026-08-24', quantity: 1, scope: 'Revisione contratti fornitori' },
		excerpt: 'ti confermo la revisione dei contratti fornitori il 24',
		confidence: 0.88
	});
	await createProposal({
		documentId: proposalsDocument.id,
		contractId: contractRow.id,
		targetType: 'work_unit',
		proposedFields: { date: '2026-08-25', quantity: 1, scope: 'Chiusura mensile di magazzino' },
		excerpt: 'e la chiusura mensile di magazzino il 25',
		confidence: 0.85
	});
}

/**
 * Bellani & Partners: continuous engagement, no prior approval, a 35%
 * client-concentration cap (AGENTS.md invariant 2 — a contract clause,
 * survives a regime change, never a pack ceiling). `2026/011` is the
 * invoice #226 names as 34 days overdue against this seed's fixed "today"
 * (issued 2026-06-10, net 30 → due 2026-07-10, 34 days before 2026-08-13).
 */
async function seedBellani() {
	const clientRow = await createClient({
		legalName: 'Bellani & Partners S.t.p.',
		taxId: 'IT01234560002',
		vatId: 'IT01234560002',
		country: 'IT',
		addressLine1: 'Via Zamboni 45',
		addressLine2: null,
		addressCity: 'Bologna',
		addressPostalCode: '40126',
		addressRegion: 'BO',
		noticeChannel: 'email',
		// #259: no CodiceDestinatario on file, but a PEC address —
		// resolves to the `'pec'` routing case.
		sdiCode: null,
		pecAddress: 'bellanipartners@pec.example.it',
		contacts: [
			{
				name: 'Marco Bellani',
				email: 'marco.bellani@bellanipartners.example',
				phone: '+39 051 555 0202',
				role: 'Socio fondatore',
				canApprove: true
			}
		]
	});

	const contractRow = await createContract({
		clientId: clientRow.id,
		title: 'Advisory continuativa — Bellani & Partners',
		signedDocumentReference: null,
		startsOn: '2024-03-01',
		endsOn: null,
		renewalType: 'tacit',
		renewalNoticeDays: 60,
		terminationNoticeDays: 30,
		paymentTerms: { kind: 'net', days: 30 },
		invoicingCadence: 'monthly',
		currency: 'EUR',
		taxTreatment: 'Regime forfettario',
		requiresPriorApproval: false,
		templateLanguage: 'it',
		expensePolicy: { kind: 'not_reimbursed' },
		requiresExpensePreAuthorisation: false,
		status: 'active'
	});

	await createRateCard({
		contractId: contractRow.id,
		validFrom: '2024-03-01',
		validTo: null,
		kind: 'daily',
		amount: 620,
		unit: 'day',
		allowedFractions: [1, 0.5],
		minimumHours: null,
		disbursementPeriod: null
	});

	await createCeiling({
		contractId: contractRow.id,
		code: 'client-concentration-cap',
		label: {
			en: 'Client concentration cap (35%)',
			it: 'Tetto di concentrazione cliente (35%)'
		},
		legalBasis: null,
		measure: 'percentage_share',
		value: 0.35,
		basis: 'invoiced_calendar_year',
		alertLevels: [
			{
				ratio: 0.8,
				label: {
					en: 'Approaching the 35% concentration cap',
					it: 'In avvicinamento al tetto di concentrazione del 35%'
				}
			},
			{
				ratio: 1,
				label: { en: 'Concentration cap reached', it: 'Tetto di concentrazione raggiunto' }
			}
		],
		consequence: {
			en: 'Review the engagement mix with the client before renewing',
			it: 'Rivedere il mix di incarichi con il cliente prima del rinnovo'
		}
	});

	const dayRate = eur(620);

	const dayOne = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-06-05',
			quantity: 1,
			scope: 'Revisione processi di approvvigionamento',
			state: 'worked'
		},
		LORENZO,
		'giornata svolta come da accordo continuativo, nessuna approvazione richiesta'
	);
	const dayTwo = await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-06-08',
			quantity: 1,
			scope: 'Workshop pianificazione strategica Q3',
			state: 'worked'
		},
		LORENZO,
		'giornata svolta come da accordo continuativo, nessuna approvazione richiesta'
	);
	await createTaxedInvoice(contractRow.id, '2026/011', '2026-06-10', '2026-07-10', [
		dayLine('Revisione processi di approvvigionamento — 05/06/2026', dayOne.id, dayRate),
		dayLine('Workshop pianificazione strategica Q3 — 08/06/2026', dayTwo.id, dayRate)
	]);

	// A more recent day, not yet on any invoice — the "continuous" half of
	// the archetype: work keeps happening between billing runs.
	await createWorkUnit(
		{
			contractId: contractRow.id,
			date: '2026-08-01',
			quantity: 1,
			scope: 'Allineamento mensile con la direzione',
			state: 'worked'
		},
		LORENZO,
		'giornata svolta come da accordo continuativo, nessuna approvazione richiesta'
	);
}

/**
 * Fermata Digitale: a flat monthly retainer, billed as one manual line
 * rather than itemised by day. `2026/015` is the invoice #226 names as due
 * in three days against this seed's fixed "today" (issued 2026-08-01,
 * due date read verbatim as 2026-08-16, three days after 2026-08-13).
 */
async function seedFermata() {
	const clientRow = await createClient({
		legalName: 'Fermata Digitale S.r.l.',
		taxId: 'IT01234560003',
		vatId: 'IT01234560003',
		country: 'IT',
		addressLine1: 'Corso Francia 88',
		addressLine2: null,
		addressCity: 'Torino',
		addressPostalCode: '10143',
		addressRegion: 'TO',
		noticeChannel: 'email',
		// #259: neither on file — resolves to the `'reserved_area'` routing
		// case, SdI's own default `'0000000'`. Deliberately the third
		// archetype: the self-hoster has to notify Fermata out-of-band,
		// same as any client whose routing address was never collected.
		sdiCode: null,
		pecAddress: null,
		contacts: [
			{
				name: 'Giulia Conti',
				email: 'giulia.conti@fermatadigitale.example',
				phone: '+39 011 555 0303',
				role: 'Head of Product',
				canApprove: false
			}
		]
	});

	const contractRow = await createContract({
		clientId: clientRow.id,
		title: 'Retainer mensile — Fermata Digitale',
		signedDocumentReference: null,
		startsOn: '2025-06-01',
		endsOn: null,
		renewalType: 'tacit',
		renewalNoticeDays: 30,
		terminationNoticeDays: 15,
		paymentTerms: { kind: 'net', days: 15 },
		invoicingCadence: 'monthly',
		currency: 'EUR',
		taxTreatment: 'Regime forfettario',
		requiresPriorApproval: false,
		templateLanguage: 'it',
		expensePolicy: { kind: 'not_reimbursed' },
		requiresExpensePreAuthorisation: false,
		status: 'active'
	});

	await createRateCard({
		contractId: contractRow.id,
		validFrom: '2025-06-01',
		validTo: null,
		kind: 'fixed_recurring',
		amount: 1800,
		unit: 'month',
		allowedFractions: [1],
		minimumHours: null,
		disbursementPeriod: 'monthly'
	});

	await createTaxedInvoice(contractRow.id, '2026/015', '2026-08-01', '2026-08-16', [
		{
			description: 'Canone mensile — agosto 2026',
			quantity: 1,
			unitPrice: eur(1800),
			amount: eur(1800),
			taxRate: TAX_TREATMENT.taxRate,
			taxTreatmentCode: TAX_TREATMENT.code,
			workUnitIds: []
		}
	]);
}

export interface SeedResult {
	alreadySeeded: boolean;
}

/** Builds the whole demo instance: one fiscal profile, three clients, each
 * with its contract, rate card and the evidence #226 asks for. Gated on
 * Nordwind Logistics' `tax_id` — present means a previous run already
 * built this instance, so nothing further is written. */
export async function seedDemo(): Promise<SeedResult> {
	const existing = await db.query.client.findFirst({
		where: eq(clientTable.taxId, 'IT01234560001')
	});
	if (existing) return { alreadySeeded: true };

	await seedFiscalProfile();
	await seedNordwind();
	await seedBellani();
	await seedFermata();

	return { alreadySeeded: false };
}
